### ISSUE TITLE
Support non-reductive amination

### ISSUE THREAD

**Issue by lukaszsobala** [margotbligh/GlycoAnnotateR#75]
Hello,

thank you for creating the package. I would like to request that you also support finding sugars labeled by non-reductive amination. It is too often an ignored labeling method.

Best regards,
Łukasz

**Comment by margotbligh** [comment]
Hello Lukasz, 

Thank you for your feedback! Apologies for the slow reply. Are there any specific labelling approaches in particular that you would find it helpful to have included? I have only worked with reductive amination so am not very familiar with the other labels.

Best,
Margot

**Comment by lukaszsobala** [comment]
Here is a sample paper: https://doi.org/10.1021/acs.analchem.0c01748 
It is only a difference of 2 Da.

**Comment by margotbligh** [comment]
I incorporated nonreductive amination for 2-AA and 3-AQ. If you have any issues with the new labels please feel free to reopen the issue :)
